services:
  user:
    build:
      context: ./user
      dockerfile: Dockerfile
    networks:
      - user-postgres
    depends_on:
      - postgres

  location:
    build:
      context: ./location
      dockerfile: Dockerfile
    networks:
      - awesome

  weather:
    build:
      context: ./weather
      dockerfile: Dockerfile
    networks:
      - awesome

  user-location:
    build:
      context: ./user-location
      dockerfile: Dockerfile
    networks:
      - awesome

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    networks:
      - awesome

  postgres:
    image: postgres
    container_name: "postgresql"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    volumes:
      - user_service:/var/lib/postgresql/data
    networks:
      - user-postgres

volumes:
  user_service:

networks:
  user-postgres:
    driver: bridge
  awesome:
    driver: bridge

